spring:
  application:
    name: pragma-ms-users
  profiles:
    include: persistence

logging:
  level:
    co.com.pragma: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
