spring:
  application:
    name: pragma-ms-users
  profiles:
    include: r2dbc
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  error:
    include-stack-trace: DEBUG

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
